version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    command: yarn dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - ".:/app"
    networks:
      rede:
        ipv4_address: 172.30.0.10
  database:
    image: mysql
    container_name: mysql_api
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "senha"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      TZ: "America/Sao_Paulo"
    networks:
      rede:
        ipv4_address: 172.30.0.11
networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
