version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    command: yarn dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - ".:/app"

  database:
    image: mysql
    cap_add:
      - SYS_NICE
    container_name: mysql_api
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "senha"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      TZ: "America/Sao_Paulo"
